### PR TITLE
Dataset Masking: Per-Sample Training Weight

### LINKED ISSUE #125: Is there a way for assigning different weights for each sample or class?
I'm dealing with multi-class classification problem with scikit-neuralnetwork, and apparently there is some class imbalance problem. So, is it possible to customize the cost function by assigning different weights for each class? Thanks.

### PR DESCRIPTION
**Pull request by alexjc**
Closes #125.

### CODE REVIEW

**Comment by alexjc** [comment]
This apparently breaks the code with non-masked data. Looking into it.

**Comment by paullo0106** [comment]
@alexjc hi Alex, I just pip install **scikit-neuralnetwork (0.4)**  and would like to use ```nn.fit(X_train, y_train, w_train)``` as shown in the [Per-sample weighting example](http://scikit-neuralnetwork.readthedocs.org/en/latest/guide_beginners.html#per-sample-weighting). However, I don't see that `w` variable in my `fit()` function in the **sknn** source code. What could be the reason? Thank you.

**Comment by alexjc** [comment]
We haven't yet pushed `fit()` with weight to PIP. It's in master only.

There's a different documentation page for `stable` (linked from PIP) here: scikit-neuralnetwork.readthedocs.org/en/stable/guide_beginners.html

**Comment by paullo0106** [comment]
Thanks Alex, let me take a look!

**Pull request merged**
