### PR TITLE
Construction from Layer specification objects.

### PR DESCRIPTION
**Pull request by alexjc**
New syntax for specifying layers that makes it easier to pass-in (and document) parameters.  This provides error checking by default, too.

Updates #3, #6, #12, #18.

### CODE REVIEW

**Comment by alexjc** [comment]
I think this one is ready for review, @ssamot. Thanks :-)

**Comment by ssamot** [comment]
I think this is overall great, but it could be the case that having just on Layer type might prove too confusing (it might make new users confused about having to define a softmax layer with  kernel). On the other hand if you have each layer type in each class it might be too confusing as well, too many objects flying around. I think the proper level of abstraction is Layer, PoolingLayer and ConvolutionLayer - what do you think?

**Comment by alexjc** [comment]
I'm not sure about having a separate Pooling layer because it's implemented as part of the convolution in `pylearn2` and therefore might be a bit fragile if we decouple it; we'd have to check that Pooling is only ever added after Convolution, and only once.

For the Convolution, that sounds reasonable... If we can support more convolution layer types at the same time, why not!  I'll make a separate ticket though.

**Comment by ssamot** [comment]
Agreed!

**Comment by alexjc** [comment]
Created new ticket #20 for improving the convolution support.

**Pull request merged**
