### PR TITLE
Doc change to GridSearchCV example

### PR DESCRIPTION
**Pull request by namebrandon**
Quotation marks around learning_rate.

### CODE REVIEW

**Comment by alexjc** [comment]
For reference: you made a new pull request, but you pushed the same branch, so it's effectively the same as the other one :-)

**Comment by namebrandon** [comment]
Oh no. I'm sorry, I'm terrible at this. Feel free to close the request, I'll just let someone who knows what they're doing make the update.  I'm sure you all have better things to do than watch me completely mess this up! :)

**Comment by alexjc** [comment]
It's a good way to learn, I'll leave this for 24h :-)  Feel free to figure it out, it's a safe change to make so why not!

**Comment by namebrandon** [comment]
I think I finally got it.. though I had to create a new branch, and then a new request.. again, I apologize for the mess!

**Pull request closed without merging**
